TEAM-BETTER/Coding_Test_Review

Coding_Test/TEST/1/testingTest01_박세원.java

0525_코딩테스트_박세원_코드

---

Coding_Test/TEST/1/codingTest[01]_[최찬호].java
Coding_Test/TEST/3/codingTest[03]_[박귀우].java

0525_코딩테스트_최찬호_코드

---

.idea/workspace.xml
Coding_Test/TEST/1/codingTest[01]_[조영진].java

0525_코딩테스트_조영진_코드

---

Coding_Test/TEST/1/Main.java
Coding_Test/TEST/1/codingTest_신소희.java

0525_코딩테스트_신소희_코드

---

Coding_Test/0526/1/codingTest01_김정민.java
Coding_Test/0526/2/codingTest02_김정민.java
Coding_Test/0526/3/codingTest03_김정민.java
Coding_Test/0526/4/codingTest04_김정민.java
Coding_Test/0526/5/codingTest05_김정민.java
Coding_Test_Review.iml

confilct file

---

.gitignore
Coding_Test/0526/1/codingTest01_김정민.java
Coding_Test/0526/2/codingTest02_김정민.java
Coding_Test/0526/3/codingTest03_김정민.java
Coding_Test/0526/4/codingTest04_김정민.java
Coding_Test/0526/5/codingTest05_김정민.java
Coding_Test_Review.iml

05_26_코딩테스트_김정민_코드

---

Coding_Test/0526/1/codingTest01_조영진.java
Coding_Test/0526/2/codingTest02_조영진.java
Coding_Test/0526/3/codingTest03_조영진.java
Coding_Test/0526/5/codingTest05_조영진.java

0526_코딩테스트_조영진_코드

---

Coding_Test/0526/1/cordingTest01_안승신.java
Coding_Test/0526/2/cordingTest02_안승신.java

0526_코딩테스트_안승신_코드

---

Coding_Test/0526/CodingTest01_최혜승.java
Coding_Test/TEST/2/codingTest01_최혜승.java

0526_코딩테스트_최혜승_코드

---

Coding_Test/0602/1/CodingTest01_정민지.java
Coding_Test/0602/2/CodingTest02_정민지.java
Coding_Test/0602/3/CodingTest03_정민지.java
Coding_Test/0602/4/CodingTest04_정민지.java

아휴우우.. 다들 너무 너무 고생하셨습니다. ㅠㅠ 잘 부탁드려요..!! ㅠㅠ

0602_코딩테스트_정민지_코드

---

Coding_Test/0602/1/CodingTest01_주익수.java
Coding_Test/0602/2/CodingTest02_주익수.java
Coding_Test/0602/5/CodingTest05_주익수.java

아.. 2, 5번문제 풀다가 시간 다 가버렸네요..
3, 4번은 리뷰받기 너무 부끄러워서 올리지 못했습니다..
가르침 부탁드립니다..

0602_코딩테스트_주익수_코드

---

Coding_Test/0602/1/codingTest01_박세원.java
Coding_Test/0602/2/codingTest02_박세원.java
Coding_Test/0602/3/codingTest03_박세원.java
Coding_Test/0602/4/codingTest04_박세원.java
Coding_Test/0602/5/codingTest05_박세원.java

익숙치 않은 자료구조 사용하다가 패닉이 와버린 이번 시험입니다.
1번은 20점중 10점짜리 코드
나머지는 테스트 종료 이후에 작성한 코드입니다.
테스트코드를 나름대로 돌려보긴 했는데, 정확하지 않습니다.
많은 비판, 비난, 욕 환영합니다.

0602_코딩테스트_박세원_코드

---

Coding_Test/0602/1/CodingTest01_김우진.java
Coding_Test/0602/2/CodingTest02_김우진.java
Coding_Test/0602/3/CodingTest03_김우진.java
Coding_Test/0602/4/CodingTest04_김우진.java
Coding_Test/0602/5/CodingTest05_김우진.java
Coding_Test/TEST/1/codingTest01_김우진.java

0602_코딩테스트_김우진_코드

---

Coding_Test/0602/1/CodingTest01_김이안.java
Coding_Test/0602/2/CodingTest02_김이안.java
Coding_Test/0602/3/CodingTest03_김이안.java
Coding_Test/0602/5/CodingTest05_김이안.java

0602_코딩테스트_김이안_코드

---

Coding_Test/0609/1/CodinTest01_이시화.java
Coding_Test/0609/2/CodinTest02_이시화.java
Coding_Test/0609/3/CodinTest03_이시화.java
Coding_Test/0609/4/CodinTest04_이시화.java
Coding_Test/0609/5/CodinTest05_이시화.java

최대한 코드를 설명한다고 했는데 말을 조리있게 하지 못해서 걱정입니다...
이해가 잘 안되시는 부분은 질문 해주시면 답변해 드리겠습니다!!
이번 커밋은 성공적으로 깔끔하게 해내었습니다.
sorcetree 라는 프로그램 사용하니까 그나마 편하네요

0609_코딩테스트_이시화_코드

---

Coding_Test/0609/1/CodingTest01_윤지용.java
Coding_Test/0609/4/CodingTest04_윤지용.java

정말 어렵네요.... 1, 4번 2개밖에 못 풀었습니다^^;; 그래도 풀리퀘 해봅니다 ㅎㅎ
지난 코드리뷰 덕분에 배운것도 적용해보고, 삼항연산자도 조금씩 익숙해지고 있습니다. 리뷰해주신 수강생분들, 함께 참여해주시는 분들 모두 감사합니다.

0609_코딩테스트_윤지용_코드

---

Coding_Test/0609/1/CodingTest01_김우진.java
Coding_Test/0609/2/CodingTest02_김우진.java
Coding_Test/0609/3/CodingTest03_김우진.java
Coding_Test/0609/5/CodingTest05_김우진.java

아직 우선순위 큐, heap 강의를 안 들어서 4번은 해당 강의 듣고 푼 뒤 pull request 요청 드리겠습니다.
2번의 경우 slack에서 강사님이 올려주신 코드를 제가 나름대로 해석해서 주석을 달아봤습니다.
comment 부탁드립니다.

0609_코딩테스트_김우진_코드

---

Coding_Test/0609/1/CodingTest01_박귀우.java
Coding_Test/0609/2/CodingTest02_박귀우.java
Coding_Test/0609/4/CodingTest04_박귀우.java

2문제 밖에 못풀었지만 pr 날려 봅니다. 감사합니다. 좋은하루 되셔요

0609_코딩테스트_박귀우

---

Coding_Test/0616/1/CodingTest01_정민지.java
Coding_Test/0616/2/CodingTest02_정민지.java
Coding_Test/0616/3/CodingTest03_정민지.java
Coding_Test/0616/4/CodingTest04_정민지.java

어제도 코딩 테스트 보시느라 너무 너무 고생하셨습니다! 4번 문제를 수정하던 중에 시간이 끝나 5번 문제는 풀지 못했고요! 4번은 효율성에서 점수가 떨어졌는데 뭔가 처리를 하나 덜 해서 그런 것 같습니다.. ㅠㅠ 혹시 문제가 있다 생각되는 부분들은 지적해주시면 감사하겠습니다! 그리고 혹시 궁금하신 부분 있으시면 댓글 남겨주세요!

0616_코딩테스트_정민지_코드

---

Coding_Test/0616/1/CodingTest01_이시화.java
Coding_Test/0616/2/CodingTest02_이시화.java
Coding_Test/0616/3/CodingTest03_이시화.java
Coding_Test/0616/4/CodingTest04_이시화.java
Coding_Test/0616/5/CodingTest05_이시화.java

1, 2, 3 번 코드는 Trie 를 사용하지 않고  풀어서 좋은 코드는 아닌 것 같습니다...
String 메소드만 참고하시면 좋을 것 같습니다.

0616_코딩테스트_이시화_코드

---

Coding_Test/0616/1/CodingTest01_김우진.java
Coding_Test/0616/2/CodingTest02_김우진.java
Coding_Test/0616/3/CodingTest03_김우진.java
Coding_Test/0616/4/CodingTest04_김우진.java
Coding_Test/0616/5/CodingTest05_김우진.java

목요일에 풀지 못했던 문제들도 풀어서 pull request 드립니다.
comment 부탁 드립니다.

0616_코딩테스트_김우진_코드

---

Coding_Test/0616/1/codingTest01_윤지용.java
Coding_Test/0616/2/codingTest02_윤지용.java
Coding_Test/0616/3/codingTest03_윤지용.java

이번 코테는 String으로 문제가 나와서,,, stratswith 메서드로 꿀을 빨아버렸네요..... 부끄럽습니다...ㅠㅠ 힙과 트라이는,,, 나중에 코테준비할때 다시 하렵니다... gg요....

0616_코딩테스트_윤지용_코드

---

Coding_Test/0623/1/CodingTest01_이시화.java
Coding_Test/0623/2/CodingTest02_이시화.java
Coding_Test/0623/3/CodingTest03_이시화.java
Coding_Test/0623/4/CodingTest04_이시화.java
Coding_Test/0623/5/CodingTest05_이시화.java

아침 10시부터 6시까지 코테를 두번이나 보니 죽을 맛이네요 ㅠㅠ
4번 코드가 다른 코드로 올라가있어서 수정하였습니다!!

0623_코딩테스트_이시화_코드

---

Coding_Test/0623/1/CodingTest01_김이안.java
Coding_Test/0623/2/CodingTest02_김이안.java
Coding_Test/0623/3/CodingTest03_김이안.java
Coding_Test/0623/4/CodingTest04_김이안.java
Coding_Test/0623/5/CodingTest05_김이안.java

2주 동안 너무 바빠서 못 올렸네요 ㅠㅠㅠㅠ
이제부터라도 매주 올리겠습니다!!

0623_코딩테스트_김이안_코드

---

Coding_Test/0623/1/CodingTest01_박귀우.java
Coding_Test/0623/2/CodingTest02_박귀우.java
Coding_Test/0623/3/CodingTest03_박귀우.java
Coding_Test/0623/4/CodingTest04_박귀우.java

잘 부탁드립니다.!! 이번 코테 도 정말 고생 많으셨습니다 !!

0623_코딩테스트_박귀우_코드

---

Coding_Test/0623/1/CodingTest1_김우진.java
Coding_Test/0623/2/CodingTest2_김우진.java
Coding_Test/0623/3/CodingTest3_김우진.java
Coding_Test/0623/4/CodingTest4_김우진.java
Coding_Test/0623/5/CodingTest5_김우진.java

안녕하세요 이번 주도 코테 보느라 다들 고생 많으셨습니다 :)

0623_코딩테스트_김우진_코드

---

Coding_Test/0623/1/CodingTest01_정민지.java
Coding_Test/0623/2/CodingTest02_정민지.java
Coding_Test/0623/3/CodingTest03_정민지.java
Coding_Test/0623/4/CodingTest04_정민지.java

안녕하세요! 다들 이번에도 너무 너무 고생하셨습니다. 원래는 어제 업로드를 했다가 다시 수정한 코드를 올려야겠다 생각해 close를 시켰었는데요. 시간도 없었고 3번을 자체적으로 수정을 해보려고 했으나 코드를 전체적으로 뜯어야 할 것 같아서 그냥 다른 분들 코드를 참고하기로 했습니다. ㅠㅠ 효율성 2개에서 막혀 16점 코드입니다.

0623_코딩테스트_정민지_코드

---

Coding_Test/0623/1/CodingTest01_윤지용.java
Coding_Test/0623/3/CodingTest03_윤지용.java
Coding_Test/0623/4/CodingTest04_윤지용.java

0623_코딩테스트_윤지용_코드

---

Coding_Test/0630/1/CodingTest01_김정민.java
Coding_Test/0630/2/CodingTest02_김정민.java
Coding_Test/0630/3/CodingTest03_김정민.java
Coding_Test/0630/4/CodingTest04_김정민.java

0630_코딩테스트_김정민_코드

---

Coding_Test/0630/1/CodingTest01_윤지용.java
Coding_Test/0630/2/CodingTest02_윤지용.java
Coding_Test/0630/3/CodingTest03_윤지용.java

1번밖에 못풀었네요 이번에는...
2번은 시간초과 나서 테스트 끝나고 조건 변경하여 완료 후 올패스까지 확인은 했습니다.
코딩테스트 보시느라 모두들 고생하셨습니다.

0630_코딩테스트_윤지용_코드

---

Coding_Test/0630/1/CodingTest01_김이안.java
Coding_Test/0630/4/CodingTest04_김이안.java

3번도 있는데 코드가 너무 엉망이라 1,4번만 올립니다!!
4번만 참고하시면 될 것 같아요 ㅎㅎ;;

0630_코딩테스트_김이안_코드

---

0714_코딩테스트_김란_2번.java
0714_코딩테스트_김란_3번.java
0714_코딩테스트_김란_4번.java
0721_코딩테스트_김란_4번.java

- 늦게 올려서 죄송합니다. ㅠㅠ
- 처음 해봐서 익숙치가 않네요.. 리뷰해주시면 감사하겠습니다.
-

0714_코딩테스트_김란_ 브랜치 만들고 올림

---

Coding_Test/0721/4/CodingTest04_김란.java

- 이번에 한 문제 밖에 못 풀었습니다.. 
- 분발하도록 하겠습니다..😂😂
-

0721_코딩테스트 리뷰_김란

---

Coding_Test/0721/1/CodingTest01_김이안.java
Coding_Test/0721/2/CodingTest02_김이안.java
Coding_Test/0721/3/CodingTest03_김이안.java
Coding_Test/0721/4/CodingTest04_김이안.java
Coding_Test/0721/5/CodingTest05_김이안.java

-  2, 3번이 16점인 코드입니다!!
- 최소신장트리는 자신 있었지만 최단거리 문제는 자신 없었는데 운 좋게 점수가 잘 나왔네요
-

0721_코딩테스트_김이안_코드

---

Coding_Test/0721/1/CodingTest01_이시화.java
Coding_Test/0721/2/CodingTest02_이시화.java
Coding_Test/0721/3/CodingTest03_이시화.java
Coding_Test/0721/4/CodingTest04_이시화.java
Coding_Test/0721/5/CodingTest05_이시화.java

0721_코딩테스트_이시화_코드

---

Coding_Test/0728/1/CodingTest1_김정민.java
Coding_Test/0728/2/CodingTest2_김정민.java
Coding_Test/0728/4/CodingTest4_김정민.java
Coding_Test/0728/5/CodingTest5_김정민.java

-  pull request 하다가 에러가 떠서 좀 늦었네요 죄송합니다
-

0728 김정민 코딩테스트

---

Coding_Test/0728/1/CodingTest01_김이안.java
Coding_Test/0728/2/CodingTest02_김이안.java
Coding_Test/0728/4/CodingTest03_김이안.java
Coding_Test/0728/5/CodingTest05_김이안.java

- 1245번 풀고 한시간 넘게 남았었는데 3번을 못풀었습니다 ㅠㅠ
-

0728_코딩테스트_김이안_코드

---

Coding_Test/0728/1/CodingTest1_김란.java
Coding_Test/0728/2/CodingTest2_김란.java
Coding_Test/0728/5/CodingTest5_김란.java
Coding_Test/0804/1/CodingTest1_김란.java
Coding_Test/0804/2/CodingTest2_김란.java
Coding_Test/0804/4/CodingTest4_김란.java
Coding_Test/0804/5/CodingTest5_김란.java

0728_김란님 코드입니다!
- 2번 감점 부분에 대해 의견 주시면 감사하겠습니다!
- (제가... 대신 올렸지만 이것은 란님의 코드입니다. ㅎㅎ 란님 pr이 조금 꼬여서 코드가 안 보이고 revert랑 이래저래.. 복잡해져서 제가 이렇게 수정해서 올립니다.)
-

0728_김란님 코드입니다!

---

Coding_Test/0804/1/CodingTest01_이시화.java
Coding_Test/0804/2/CodingTest02_이시화.java
Coding_Test/0804/3/CodingTest03_이시화.java
Coding_Test/0804/4/CodingTest04_이시화.java
Coding_Test/0804/5/CodingTest05_이시화.java

-  잘 풀었습니다.!! 프로젝트 잘 마치고 part 2 코테에서도 힘내봅시다!!
-

0804_코딩테스트_이시화_코드

---

Coding_Test/0804/1/CodingTest01_김이안.java
Coding_Test/0804/2/CodingTest02_김이안.java
Coding_Test/0804/3/CodingTest03_김이안.java
Coding_Test/0804/5/CodingTest05_김이안.java

- 제가 지금 코로나 때문에 몸이 많이 안 좋기도 하고 스프링 과제도 해야 하는 상황이라 주석은 다음주에라도 달겠습니다 죄송합니다 ㅠㅠㅠㅠㅠ
- 1번 10/10, 2번 10/4, 3번 20, 5번 20 입니다!!
- 다들 아프지 마시고 늘 건강하세요!!!!!!
-

0804_코딩테스트_김이안_코드

---

Coding_Test/0818/1/CodingTest01_박귀우.java
Coding_Test/0818/2/CodingTest02_박귀우.java
Coding_Test/0818/3/CodingTest03_박귀우.java
Coding_Test/0818/4/CodingTest04_박귀우.java

- 3번 5번 너무어렵고 ptsd 오네요 ... ㅠ
- 늦어서 죄송합니다 좋은하루 되셔요!
-

8월18일 박귀우 코테 리뷰 입니다.
